---
galaxy_info:
  role_name: kibana
  author: Fedele Mantuano
  description: Kibana for Linux
  company: "Fedele Mantuano"
  license: "license (Apache)"
  min_ansible_version: 2.5.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system

dependencies: []
